### ISSUE TITLE
怎么配置机器人才会回复呢？

### ISSUE THREAD

**Issue by nitlei** [MoRanYue/MomoonBot#17]
我开始修改config.json里的端口就会报错JSON错误，然后没做任何修改能运行了。也与openshamrock通讯正常了。就是不知道怎能让机器人说话。
![Image_1709957960515](https://github.com/MoRanYue/MomoonBot/assets/161731456/1a67d6d4-2063-493e-a3ba-1b957c8c220b)

**Comment by MoRanYue** [comment]
a，抱歉，这里，暂时没有，编写配置文档呀……
（其实，这里，一点没有想过，这个项目，会被其他人发现，并使用呀）

emm，应该可以见到，`config.json`文件中，有1项，叫做`prompt`，它位于`listener`→`command`中呀。亦表示，需要向 Bot 后端，发送命令，便需要，在命令内容之前，加入该配置中的任何1个符号。

这是默认的配置呀：

![配置项](https://github.com/MoRanYue/MomoonBot/assets/84905594/43a69a3f-1234-4e36-8fb7-36b13abca6ee)

emm，例如：

若想要，向 Bot 发送“今日数字”，便可以发送：`.今日数字` `!今日数字` `！今日数字` `#今日数字` ，它们之中的任何1个呀
